"""
BrowserBlockFix — curl first, headless browser fallback when WAF blocks.

Simple middleware:
  1. Try request with curl (fast, lightweight)
  2. If WAF blocks → spawn headless Chrome via Playwright
  3. Route subsequent requests through browser
  4. Auto-close browser on exit

Usage (context manager):
    with BrowserBlockFix("https://target.com", "programname") as bbf:
        resp = bbf.get("/admin")
        resp = bbf.post("/login", json={"user": "admin", "pass": "123"})

Usage (manual):
    bbf = BrowserBlockFix("https://target.com")
    resp = bbf.get("/page")
    bbf.done()

Integration in other harnesses:
    from agents.browser_block_fix import BrowserBlockFix

    with BrowserBlockFix(target, program) as bbf:
        resp = bbf.get("/endpoint")
        # WAF blocked? bbf auto-spawns browser and retries transparently.
"""

from __future__ import annotations

import html
import json
import random
import subprocess
import shlex
import time
from typing import Optional
from urllib.parse import urlparse


# ---------------------------------------------------------------------------
# WAF signatures — (content_needle, waf_name) or (header_key, header_needle, waf_name)
# ---------------------------------------------------------------------------

_CONTENT_SIGS: list[tuple[str, str]] = [
    ("attention required", "Cloudflare"),        # CF challenge page title
    ("cf-ray", "Cloudflare"),                    # CF body leak
    ("checking your browser", "Cloudflare"),
    ("ray id:", "Cloudflare"),
    ("reference #", "Akamai"),
    ("akamai", "Akamai"),
    ("as-dos-cid", "Akamai"),
    ("incapsula incident id", "Imperva"),
    ("incapsula", "Imperva"),
    ("sucuri website firewall", "Sucuri"),
    ("generated by wordfence", "Wordfence"),
    ("wordfence.com", "Wordfence"),
    ("modsecurity", "ModSecurity"),
    ("mod_security", "ModSecurity"),
    ("fortiweb", "FortiWeb"),
    ("attack id:", "FortiWeb"),
    ("ddos protection by", "DDoS-Guard"),
    ("ddos-guard", "DDoS-Guard"),
    ("px-captcha", "PerimeterX"),
    ("pxi.pub", "PerimeterX"),
    ("datadome", "DataDome"),
    ("bigipserver", "F5 BIG-IP"),
    ("support id", "F5 BIG-IP"),
]

_HEADER_SIGS: list[tuple[str, str, str]] = [
    # (header_key_lower, value_needle_lower, waf_name)
    ("server", "akamaighost", "Akamai"),
    ("server", "akamai", "Akamai"),
    ("x-cache", "error from cloudfront", "AWS WAF"),
    ("server", "awselb", "AWS WAF"),
    ("server", "cloudfront", "AWS WAF"),
    ("cf-ray", "", "Cloudflare"),
    ("x-sucuri-id", "", "Sucuri"),
    ("x-datadome-cid", "", "DataDome"),
    ("x-iinfo", "", "Imperva"),
]

_BLOCK_STATUS_CODES: set[int] = {403, 406, 429, 503}


# ---------------------------------------------------------------------------
# Stealth init script — injected before any page JS runs.
# Patches the properties Akamai Bot Manager fingerprints.
# ---------------------------------------------------------------------------

_STEALTH_INIT_SCRIPT = """
// 1. Hide navigator.webdriver
Object.defineProperty(navigator, 'webdriver', { get: () => undefined });

// 2. Restore window.chrome (absent in headless)
if (!window.chrome) {
    window.chrome = {
        app: { isInstalled: false, InstallState: {}, RunningState: {} },
        csi: function() {},
        loadTimes: function() {},
        runtime: {}
    };
}

// 3. Fix navigator.plugins — headless returns empty array
if (navigator.plugins.length === 0) {
    const fakePlugins = [
        { name: 'Chrome PDF Plugin',     filename: 'internal-pdf-viewer', description: 'Portable Document Format' },
        { name: 'Chrome PDF Viewer',     filename: 'mhjfbmdgcfjbbpaeojofohoefgiehjai', description: '' },
        { name: 'Native Client',         filename: 'internal-nacl-plugin', description: '' },
    ];
    Object.defineProperty(navigator, 'plugins', {
        get: () => {
            const arr = fakePlugins.map(p => {
                const plugin = { name: p.name, filename: p.filename, description: p.description, length: 0 };
                return plugin;
            });
            arr.item = (i) => arr[i];
            arr.namedItem = (n) => arr.find(p => p.name === n) || null;
            arr.length = arr.length;
            return arr;
        }
    });
}

// 4. Fix navigator.mimeTypes
if (navigator.mimeTypes.length === 0) {
    Object.defineProperty(navigator, 'mimeTypes', {
        get: () => {
            const types = [
                { type: 'application/pdf', suffixes: 'pdf', description: '', enabledPlugin: null },
                { type: 'application/x-nacl', suffixes: '', description: 'Native Client Executable', enabledPlugin: null },
            ];
            types.item = (i) => types[i];
            types.namedItem = (n) => types.find(t => t.type === n) || null;
            types.length = types.length;
            return types;
        }
    });
}

// 5. Realistic language/platform
Object.defineProperty(navigator, 'languages', { get: () => ['en-US', 'en'] });
Object.defineProperty(navigator, 'platform', { get: () => 'Win32' });
Object.defineProperty(navigator, 'hardwareConcurrency', { get: () => 8 });
Object.defineProperty(navigator, 'deviceMemory', { get: () => 8 });

// 6. Notification permissions — headless often returns 'denied' immediately
const origQuery = window.Notification
    ? window.Notification.requestPermission
    : undefined;
if (origQuery) {
    window.Notification.requestPermission = () => Promise.resolve('default');
}

// 7. Pass permissions query (Akamai checks this)
const origPermissions = navigator.permissions && navigator.permissions.query;
if (origPermissions) {
    navigator.permissions.query = (parameters) => {
        if (parameters.name === 'notifications') {
            return Promise.resolve({ state: 'prompt', onchange: null });
        }
        return origPermissions.call(navigator.permissions, parameters);
    };
}

// 8. Realistic screen dimensions
Object.defineProperty(screen, 'width',       { get: () => 1920 });
Object.defineProperty(screen, 'height',      { get: () => 1080 });
Object.defineProperty(screen, 'availWidth',  { get: () => 1920 });
Object.defineProperty(screen, 'availHeight', { get: () => 1040 });
Object.defineProperty(screen, 'colorDepth',  { get: () => 24 });
Object.defineProperty(screen, 'pixelDepth',  { get: () => 24 });
"""


# ---------------------------------------------------------------------------
# BrowserBlockFix
# ---------------------------------------------------------------------------

class BrowserBlockFix:
    """Transparent curl → browser fallback middleware."""

    def __init__(self, target: str, program: str | None = None):
        self.target = target.rstrip("/")
        self.program = program
        self._browser_active = False
        self._dialog_detected = False
        self._waf_blocked = False

        # Playwright handles
        self._p = None
        self._browser = None
        self._context = None
        self._page = None

    # -----------------------------------------------------------------------
    # curl helpers
    # -----------------------------------------------------------------------

    def curl_get(self, path: str, headers: dict | None = None) -> dict:
        """Quick GET with curl. Returns response dict."""
        url = self._url(path)
        cmd = ["curl", "-sS", "-L", "--max-time", "15",
               "-w", "\n__STATUS__:%{http_code}",
               "-D", "-",   # dump headers to stdout
               url]
        cmd += self._header_args(headers)
        return self._run_curl(cmd, url)

    def curl_post(self, path: str, data: dict | None = None,
                  json: dict | None = None,
                  headers: dict | None = None) -> dict:
        """POST with curl."""
        url = self._url(path)
        cmd = ["curl", "-sS", "-L", "--max-time", "15",
               "-w", "\n__STATUS__:%{http_code}",
               "-D", "-",
               "-X", "POST"]
        if json is not None:
            body = __import__("json").dumps(json)
            cmd += ["-H", "Content-Type: application/json", "-d", body]
        elif data is not None:
            for k, v in data.items():
                cmd += ["--data-urlencode", f"{k}={v}"]
        cmd += self._header_args(headers)
        cmd.append(url)
        return self._run_curl(cmd, url)

    # -----------------------------------------------------------------------
    # WAF detection
    # -----------------------------------------------------------------------

    def is_blocked(self, response: dict) -> tuple[bool, str | None]:
        """Return (True, waf_name) if response looks like a WAF block."""
        content = html.unescape(response.get("content", "")).lower()
        headers = {k.lower(): v.lower() for k, v in response.get("headers", {}).items()}
        status = response.get("status", 0)

        # Content signatures
        for needle, name in _CONTENT_SIGS:
            if needle in content:
                return True, name

        # Header signatures
        for hdr_key, hdr_needle, name in _HEADER_SIGS:
            if hdr_key in headers:
                if not hdr_needle or hdr_needle in headers[hdr_key]:
                    return True, name

        # Block status + generic cloud/WAF indicators
        if status in _BLOCK_STATUS_CODES:
            server = headers.get("server", "")
            for waf in ("akamai", "cloudflare", "imperva", "sucuri", "wordfence", "fortiweb"):
                if waf in server:
                    return True, waf.capitalize()
            for keyword in ("cloudflare", "akamai", "imperva", "sucuri",
                            "aws", "firewall", "blocked", "captcha"):
                if keyword in content:
                    return True, keyword.capitalize()

        return False, None

    # -----------------------------------------------------------------------
    # Browser management
    # -----------------------------------------------------------------------

    def spawn_browser(self) -> None:
        """Spawn headless Chrome via Playwright with Akamai stealth patches."""
        if self._browser_active:
            return
        try:
            from playwright.sync_api import sync_playwright
        except ImportError as e:
            raise RuntimeError(
                "playwright not installed — run: pip install playwright && playwright install chromium"
            ) from e

        self._p = sync_playwright().start()
        self._browser = self._p.chromium.launch(
            headless=True,
            args=[
                "--disable-blink-features=AutomationControlled",
                "--disable-features=IsolateOrigins,site-per-process",
                "--no-sandbox",
                "--disable-setuid-sandbox",
                "--disable-dev-shm-usage",
                "--disable-accelerated-2d-canvas",
                "--no-first-run",
                "--no-zygote",
                "--disable-gpu",
                "--window-size=1280,800",
                "--lang=en-US,en",
            ],
        )
        self._context = self._browser.new_context(
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/124.0.0.0 Safari/537.36"
            ),
            viewport={"width": 1280, "height": 800},
            locale="en-US",
            timezone_id="America/New_York",
            color_scheme="light",
            extra_http_headers={
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
                "Accept-Language": "en-US,en;q=0.9",
                "Accept-Encoding": "gzip, deflate, br",
                "Upgrade-Insecure-Requests": "1",
                "Sec-Fetch-Dest": "document",
                "Sec-Fetch-Mode": "navigate",
                "Sec-Fetch-Site": "none",
                "Sec-Fetch-User": "?1",
                "Sec-Ch-Ua": '"Chromium";v="124", "Google Chrome";v="124", "Not-A.Brand";v="99"',
                "Sec-Ch-Ua-Mobile": "?0",
                "Sec-Ch-Ua-Platform": '"Windows"',
            },
        )

        # Patch JS fingerprints that Akamai Bot Manager inspects
        self._context.add_init_script(_STEALTH_INIT_SCRIPT)

        self._page = self._context.new_page()
        self._browser_active = True
        print(f"[browser_block_fix] Stealth browser spawned for {self.target}")

    def close_browser(self) -> None:
        """Close browser and Playwright instance."""
        if not self._browser_active:
            return
        try:
            if self._browser:
                self._browser.close()
            if self._p:
                self._p.stop()
        except Exception:
            pass
        finally:
            self._p = None
            self._browser = None
            self._context = None
            self._page = None
            self._browser_active = False

    # -----------------------------------------------------------------------
    # Browser requests
    # -----------------------------------------------------------------------

    def browser_get(self, path: str) -> dict:
        """GET through headless browser."""
        url = self._url(path)
        try:
            resp = self._page.goto(url, wait_until="networkidle", timeout=30_000)
            return {
                "success": bool(resp and resp.ok),
                "status": resp.status if resp else 0,
                "content": self._page.content(),
                "headers": dict(resp.headers) if resp else {},
                "url": self._page.url,
                "via": "browser",
            }
        except Exception as exc:
            return _error_response(url, str(exc), via="browser")

    def browser_post(self, path: str, data: dict | None = None,
                     json: dict | None = None) -> dict:
        """POST through headless browser — fills form fields then submits."""
        url = self._url(path)
        payload = json if json is not None else (data or {})

        try:
            self._page.goto(url, wait_until="domcontentloaded", timeout=30_000)

            for key, value in payload.items():
                selector = f"[name={key}], [id={key}], input[placeholder*={key}]"
                try:
                    self._page.click(selector, timeout=2_000)
                    # Human-like typing with small random delays
                    self._page.type(selector, str(value), delay=random.randint(40, 120))
                    time.sleep(random.uniform(0.1, 0.3))
                except Exception:
                    pass  # field not found — best effort

            time.sleep(random.uniform(0.3, 0.7))

            # Try submit button; fall back to keyboard Enter
            try:
                self._page.click("[type=submit]", timeout=3_000)
            except Exception:
                self._page.keyboard.press("Enter")

            self._page.wait_for_load_state("networkidle", timeout=15_000)

            return {
                "success": True,
                "status": 200,
                "content": self._page.content(),
                "headers": {},
                "url": self._page.url,
                "via": "browser",
            }
        except Exception as exc:
            return _error_response(url, str(exc), via="browser")

    # -----------------------------------------------------------------------
    # Public API — auto fallback
    # -----------------------------------------------------------------------

    def get(self, path: str, headers: dict | None = None) -> dict:
        """GET: curl first. If WAF blocks, spawn browser and retry."""
        # If browser already active, skip curl entirely
        if self._browser_active:
            return self.browser_get(path)

        response = self.curl_get(path, headers=headers)
        blocked, waf_name = self.is_blocked(response)
        if not blocked:
            return response

        print(f"[browser_block_fix] WAF blocked ({waf_name}) — spawning browser...")
        self.spawn_browser()
        return self.browser_get(path)

    def post(self, path: str, data: dict | None = None,
             json: dict | None = None,
             headers: dict | None = None) -> dict:
        """POST: curl first. If WAF blocks, spawn browser and retry."""
        if self._browser_active:
            return self.browser_post(path, data=data, json=json)

        response = self.curl_post(path, data=data, json=json, headers=headers)
        blocked, waf_name = self.is_blocked(response)
        if not blocked:
            return response

        print(f"[browser_block_fix] WAF blocked ({waf_name}) — spawning browser...")
        self.spawn_browser()
        return self.browser_post(path, data=data, json=json)

    def test_xss_payload(self, url: str, payload: str, param: str = "q") -> dict:
        """Test an XSS payload via browser.

        Returns dict with:
            - executed: bool (dialog detected)
            - reflected: bool (payload in response)
            - blocked: bool (WAF blocked)
            - response_text: str
        """
        from urllib.parse import urlencode, urlparse, parse_qs, urlunparse

        parsed = urlparse(url)
        qs = parse_qs(parsed.query, keep_blank_values=True)
        qs[param] = [payload]
        new_query = urlencode({k: v[0] for k, v in qs.items()})
        test_url = urlunparse(parsed._replace(query=new_query))

        if not self._browser_active:
            self.spawn_browser()

        # Reset dialog state before navigation
        self._dialog_detected = False
        self._waf_blocked = False

        try:
            from playwright.sync_api import sync_playwright as _sp  # already imported if active
        except ImportError:
            pass

        # Attach dialog handler
        def _on_dialog(dialog):
            self._dialog_detected = True
            try:
                dialog.dismiss()
            except Exception:
                pass

        self._page.on("dialog", _on_dialog)

        try:
            resp = self._page.goto(test_url, wait_until="domcontentloaded", timeout=20_000)
            self._page.wait_for_timeout(1000)
            content = self._page.content()
            status = resp.status if resp else 0
        except Exception as exc:
            content = ""
            status = 0

        self._page.remove_listener("dialog", _on_dialog)

        blocked, _ = self.is_blocked({"content": content, "status": status, "headers": {}})
        self._waf_blocked = blocked

        return {
            "executed": self._dialog_detected,
            "reflected": payload in content,
            "blocked": blocked,
            "response_text": content,
        }

    def done(self) -> None:
        """Close browser when finished."""
        self.close_browser()

    # -----------------------------------------------------------------------
    # Context manager
    # -----------------------------------------------------------------------

    def __enter__(self) -> "BrowserBlockFix":
        return self

    def __exit__(self, exc_type, exc_val, exc_tb) -> bool:
        self.done()
        return False

    # -----------------------------------------------------------------------
    # Internal helpers
    # -----------------------------------------------------------------------

    def _url(self, path: str) -> str:
        if path.startswith(("http://", "https://")):
            return path
        return self.target + "/" + path.lstrip("/")

    @staticmethod
    def _header_args(headers: dict | None) -> list[str]:
        args: list[str] = []
        for k, v in (headers or {}).items():
            args += ["-H", f"{k}: {v}"]
        return args

    @staticmethod
    def _run_curl(cmd: list[str], url: str) -> dict:
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=20)
            raw = result.stdout

            # Parse status code appended by -w flag
            status = 0
            content = raw
            if "\n__STATUS__:" in raw:
                body_part, status_part = raw.rsplit("\n__STATUS__:", 1)
                content = body_part
                try:
                    status = int(status_part.strip())
                except ValueError:
                    pass

            # Parse headers from -D - output (first block before empty line)
            headers: dict[str, str] = {}
            body = content
            if "\r\n\r\n" in content:
                hdr_block, body = content.split("\r\n\r\n", 1)
                for line in hdr_block.splitlines()[1:]:  # skip status line
                    if ":" in line:
                        k, _, v = line.partition(":")
                        headers[k.strip().lower()] = v.strip()
            elif "\n\n" in content:
                hdr_block, body = content.split("\n\n", 1)
                for line in hdr_block.splitlines()[1:]:
                    if ":" in line:
                        k, _, v = line.partition(":")
                        headers[k.strip().lower()] = v.strip()

            return {
                "success": 200 <= status < 300,
                "status": status,
                "content": body,
                "headers": headers,
                "url": url,
                "via": "curl",
            }
        except subprocess.TimeoutExpired:
            return _error_response(url, "curl timeout", via="curl")
        except Exception as exc:
            return _error_response(url, str(exc), via="curl")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _error_response(url: str, error: str, via: str = "curl") -> dict:
    return {
        "success": False,
        "status": 0,
        "content": "",
        "headers": {},
        "url": url,
        "error": error,
        "via": via,
    }
