"""Shared report-path and report-writing helpers for BaseTeam-backed teams."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Callable

from agents.bounty_core_bootstrap import ensure_bounty_core_importable

ensure_bounty_core_importable()

from bounty_core.reports import (  # noqa: E402
    DAILY_REPORT_DATE_FORMAT,
    daily_report_paths,
    write_finding_report,
    write_daily_report_views,
)


def _dated_report_index_paths_for_buckets(storage, *, buckets: tuple[str, ...]) -> dict[str, Path]:
    report_date = datetime.now().strftime(DAILY_REPORT_DATE_FORMAT)
    daily_paths = daily_report_paths(storage, report_date)
    paths: dict[str, Path] = {}
    for bucket in buckets:
        paths[bucket] = daily_paths[bucket]
    return paths


def dated_report_index_paths(storage) -> tuple[Path, Path, Path]:
    """Return the new daily status report paths.

    Kept for compatibility with older callers that destructure this helper.
    It no longer creates legacy status-first dated directories.
    """
    paths = _dated_report_index_paths_for_buckets(storage, buckets=("confirmed", "dormant", "novel"))
    return paths["confirmed"], paths["dormant"], paths["novel"]


def write_report_indexes(
    storage,
    *,
    confirmed: list[dict],
    dormant: list[dict],
    novel: list[dict],
    render_confirmed: Callable[[list[dict]], str],
    render_dormant: Callable[[list[dict]], str],
    render_novel: Callable[[list[dict]], str],
) -> tuple[Path | None, Path | None, Path | None]:
    """Write the new daily link-only report views for promoted findings.

    The renderer callables are retained for API compatibility with older tests
    and callers. They are intentionally not invoked here: daily views are
    generated by bounty-core so they only link to canonical
    `reports/findings/<lifecycle>/<FID> - <SEVERITY> - <title>.md` bodies.
    """
    _ = (render_confirmed, render_dormant, render_novel)
    for finding in [*confirmed, *dormant, *novel]:
        report_path = write_finding_report(storage, finding)
        finding["report_path"] = str(report_path)

    paths = write_daily_report_views(
        storage,
        confirmed=confirmed,
        dormant=dormant,
        novel=novel,
    )
    if not paths:
        return None, None, None
    return paths["confirmed"], paths["dormant"], paths["novel"]
